const state={conversations:JSON.parse(localStorage.getItem("aura_conversations")||"[]"),current:null,models:[],attachment:null,settings:JSON.parse(localStorage.getItem("aura_settings")||"{}")};
const $=id=>document.getElementById(id);
const save=()=>localStorage.setItem("aura_conversations",JSON.stringify(state.conversations));
const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
function newConversation(){state.current={id:crypto.randomUUID(),title:"New conversation",messages:[],model:$("modelSelect").value||"",createdAt:Date.now()};state.conversations.unshift(state.current);save();render();$("prompt").focus()}
function render(){const list=$("chatList");list.innerHTML="";state.conversations.slice(0,30).forEach(c=>{const b=document.createElement("button");b.className="chat-item"+(state.current?.id===c.id?" active":"");b.textContent=c.title||"New conversation";b.onclick=()=>{state.current=c;render()};list.appendChild(b)});const box=$("messages");box.innerHTML="";if(!state.current||!state.current.messages.length){$("welcome").classList.remove("hidden");return}$("welcome").classList.add("hidden");state.current.messages.forEach(m=>addMessage(m.role,m.content,false));box.scrollTop=box.scrollHeight}
function addMessage(role,text,scroll=true){const row=document.createElement("div");row.className="message "+role;const av=document.createElement("div");av.className="avatar";av.textContent=role==="user"?"You":"✦";const b=document.createElement("div");b.className="bubble";b.innerHTML=role==="assistant"?markdown(text):escapeHtml(text);if(role==="user"){row.appendChild(b);row.appendChild(av)}else{row.appendChild(av);row.appendChild(b)}$("messages").appendChild(row);if(scroll)row.scrollIntoView({behavior:"smooth",block:"end"});return b}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function markdown(s){let x=escapeHtml(s);x=x.replace(/```([\s\S]*?)```/g,"<pre><code>$1</code></pre>");x=x.replace(/`([^`]+)`/g,"<code>$1</code>");x=x.replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");x=x.replace(/\n/g,"<br>");return x}
async function loadModels(){try{const r=await fetch("/api/models");if(!r.ok)throw new Error();const d=await r.json();state.models=d.data||[];const select=$("modelSelect");select.innerHTML="";state.models.sort((a,b)=>(a.name||a.id).localeCompare(b.name||b.id)).forEach(m=>{const o=document.createElement("option");o.value=m.id;o.textContent=m.name?`${m.name} · ${m.id}`:m.id;select.appendChild(o)});if(state.settings.model&&state.models.some(m=>m.id===state.settings.model))select.value=state.settings.model;$("modelStatus").textContent=state.models.length+" models";if(!state.current)newConversation()}catch(e){$("modelStatus").textContent="Backend belum aktif";toast("Jalankan server.js terlebih dahulu")}}
async function send(){const input=$("prompt");const text=input.value.trim();if(!text&&!state.attachment)return;if(!state.current)newConversation();if(!state.current.title||state.current.title==="New conversation"){state.current.title=(text||"Attachment").slice(0,42)}const content=text+(state.attachment?`\n\n[Attachment: ${state.attachment.name}]`:"");state.current.messages.push({role:"user",content});addMessage("user",content);input.value="";input.style.height="auto";$("sendBtn").disabled=true;const bubble=addMessage("assistant","");let full="";const payload={model:$("modelSelect").value,messages:state.current.messages.map(x=>({role:x.role,content:x.content})),temperature:Number($("temperature").value),max_tokens:Number($("maxTokens").value),system_prompt:$("systemPrompt").value};try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const err=await r.text();throw new Error(err||"Request failed")}if(!r.body)throw new Error("Streaming tidak didukung");const reader=r.body.getReader(),dec=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;full+=dec.decode(value,{stream:true});bubble.innerHTML=markdown(full);bubble.parentElement.scrollIntoView({behavior:"smooth",block:"end"})}state.current.messages.push({role:"assistant",content:full});state.current.model=payload.model;state.settings.model=payload.model;localStorage.setItem("aura_settings",JSON.stringify(state.settings));save();$("usage").textContent="Completed"}catch(e){bubble.textContent="⚠ "+e.message;toast("Gagal menghubungi AI")}finally{$("sendBtn").disabled=false;state.attachment=null;$("attachment").classList.add("hidden");render()}}

$("composer").addEventListener("submit",e=>{e.preventDefault();send()});
$("prompt").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}});
$("prompt").addEventListener("input",e=>{e.target.style.height="auto";e.target.style.height=Math.min(e.target.scrollHeight,160)+"px"});
$("newChat").onclick=newConversation;
$("themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("aura_theme",document.body.classList.contains("light")?"light":"dark")};
$("clearBtn").onclick=()=>{if(confirm("Hapus seluruh riwayat percakapan?")){state.conversations=[];state.current=null;save();newConversation()}};
$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");
$("settingsBtn").onclick=()=>{const d=$("settings");$("systemPrompt").value=state.settings.systemPrompt||"";$("temperature").value=state.settings.temperature??.7;$("maxTokens").value=state.settings.maxTokens??2048;updateRanges();d.showModal()};
$("closeSettings").onclick=()=>$("settings").close();
$("saveSettings").onclick=()=>{state.settings={...state.settings,systemPrompt:$("systemPrompt").value,temperature:Number($("temperature").value),maxTokens:Number($("maxTokens").value),model:$("modelSelect").value};localStorage.setItem("aura_settings",JSON.stringify(state.settings));$("settings").close();toast("Settings saved")};
$("resetSettings").onclick=()=>{$("systemPrompt").value="";$("temperature").value=.7;$("maxTokens").value=2048;updateRanges()};
function updateRanges(){$("tempValue").value=$("temperature").value;$("tempValue").textContent=$("temperature").value;$("tokenValue").value=$("maxTokens").value;$("tokenValue").textContent=$("maxTokens").value}
$("temperature").oninput=updateRanges;$("maxTokens").oninput=updateRanges;
$("fileInput").onchange=e=>{const f=e.target.files[0];if(!f)return;state.attachment=f;$("attachment").textContent="📎 "+f.name+" · "+Math.round(f.size/1024)+" KB";$("attachment").classList.remove("hidden");toast("Attachment dipilih")};
document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>{$("prompt").value=b.dataset.prompt;$("prompt").focus()});
if(localStorage.getItem("aura_theme")==="light")document.body.classList.add("light");
updateRanges();loadModels();
